=== K-Tamas01/N7D1L5_XMLGyak/XML_N7D1L5_Beadandó/XMLN7D1L5.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="kocsik" type="kocsiTipus">
		<xs:key name="K1">
				<xs:selector xpath="elado" />
				<xs:field xpath="@id" />
			</xs:key>
			<xs:key name="K2">
				<xs:selector xpath="gyarto" />
				<xs:field xpath="@id" />
			</xs:key>
			<xs:key name="K3">
				<xs:selector xpath="dolgozo" />
				<xs:field xpath="@id" />
			</xs:key>
			<xs:key name="K4">
				<xs:selector xpath="auto" />
				<xs:field xpath="@id" />
			</xs:key>
			<xs:key name="K5">
				<xs:selector xpath="motor" />
				<xs:field xpath="@id" />
			</xs:key>
			
			<xs:keyref refer="K1" name="refK1">
				<xs:selector xpath="kiszallitas" />
				<xs:field xpath="@GYID" />
			</xs:keyref>
			<xs:keyref refer="K2" name="refK2_1">
				<xs:selector xpath="kiszallitas" />
				<xs:field xpath="@EID" />
			</xs:keyref>
			<xs:keyref refer="K2" name="refK2_2">
				<xs:selector xpath="gyar" />
				<xs:field xpath="@GYID" />
			</xs:keyref>
			<xs:keyref refer="K3" name="refK3_1">
				<xs:selector xpath="gyar" />
				<xs:field xpath="@DID" />
			</xs:keyref>
			<xs:keyref refer="K3" name="refK3_2">
				<xs:selector xpath="gyar" />
				<xs:field xpath="@GYID" />
			</xs:keyref>
			<xs:keyref refer="K4" name="refK4_1">
				<xs:selector xpath="gyar" />
				<xs:field xpath="@KID" />
			</xs:keyref>
			<xs:keyref refer="K4" name="refK4_2">
				<xs:selector xpath="alkatresz" />
				<xs:field xpath="@KID" />
			</xs:keyref>
			<xs:keyref refer="K5" name="refK5_1">
				<xs:selector xpath="alkatresz" />
				<xs:field xpath="@MID" />
			</xs:keyref>
		</xs:element>
			
			<xs:complexType name="kocsiTipus">
				<xs:sequence>
					<xs:element name="elado" type="eladoTipus" minOccurs="0" maxOccurs="100"/> 
					<xs:element name="kiszallitas" type="kiszallitasTipus" minOccurs="0" maxOccurs="100"/>
					<xs:element name="gyarto" type="gyartoTipus" minOccurs="0" maxOccurs="100"/>
					<xs:element name="gyar" type="gyarTipusd" minOccurs="0" maxOccurs="100"/>
                    <xs:element name="gyar" type="gyarTipusk" minOccurs="0" maxOccurs="100"/>
					<xs:element name="dolgozo" type="dolgozoTipus" minOccurs="0" maxOccurs="100"/>
					<xs:element name="kocsi" type="kocsiTipus" minOccurs="0" maxOccurs="100"/>
					<xs:element name="alkatresz" type="alkatreszTipus" minOccurs="0" maxOccurs="100"/>
					<xs:element name="motor" type="motorTipus" minOccurs="0" maxOccurs="100"/>
				</xs:sequence>
			</xs:complexType>
		
			
			<xs:complexType name="eladoTipus">
				<xs:sequence>
					<xs:element name="Etulaj" type="xs:string"/>
					<xs:element name="Eadsz" type="xs:unsignedLong"/>
					<xs:element name="Ecim" type="xs:string"/>
                    <xs:element name="Eneve" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="EID" type="xs:string" use="required"/> 
			</xs:complexType>
			
			<xs:complexType name="kiszallitasTipus">
				<xs:attribute name="EID" type="xs:string" use="required"/> 
				<xs:attribute name="GYID" type="xs:string" use="required"/>
			</xs:complexType>
			
			<xs:complexType name="gyartoTipus">
				<xs:sequence>
					<xs:element name="gyneve" type="xs:string"/>
					<xs:element name="gytulaj" type="xs:string"/>
                    <xs:element name="gycim" type="xs:string"/>
					<xs:element name="gyadsz" type="xs:unsignedLong"/>
				</xs:sequence>
                <xs:attribute name="GYID" type="xs:string" use="required"/>
			</xs:complexType>
			
			<xs:complexType name="gyarTipusd">
				<xs:attribute name="GYID" type="xs:string" use="required"/> 
				<xs:attribute name="DID" type="xs:string" use="required"/>
			</xs:complexType>

            <xs:complexType name="gyarTipusk">
				<xs:attribute name="GYID" type="xs:string" use="required"/> 
				<xs:attribute name="KID" type="xs:string" use="required"/>
			</xs:complexType>
			
			<xs:complexType name="dolgozoTipus">
				<xs:sequence>
					<xs:element name="dneve" type="xs:string"/>
					<xs:element name="dtel" type="xs:string"/>
					<xs:element name="dcime" type="xs:lakhely"/>
					<xs:element name="dszul" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="DID" type="xs:string" use="required"/> 
			</xs:complexType>

			<xs:complexType name="lakhelyTipus">
				<xs:sequence>
					<xs:element name="varos" type="xs:string"/>
					<xs:element name="utca" type="xs:string"/>
					<xs:element name="irsz" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			
			<xs:complexType name="kocsiTipus">
				<xs:sequence>
					<xs:element name="kneve" type="xs:string"/>
					<xs:element name="ktip" type="xs:string"/>
					<xs:element name="khajt" type="xs:string"/>		
				</xs:sequence>
				<xs:attribute name="KID" type="xs:string" use="required"/> 
			</xs:complexType>

            <xs:complexType name="alkatreszTipus">
				<xs:attribute name="KID" type="xs:string" use="required"/> 
				<xs:attribute name="MID" type="xs:string" use="required"/>
			</xs:complexType>
			
			<xs:complexType name="motorTipus">
				<xs:sequence>
					<xs:element name="urtart" type="xs:unsignedLong"/>
					<xs:element name="mtip" type="xs:string"/>
                    <xs:element name="telj" type="xs:unsignedLong"/>
				</xs:sequence>
                <xs:attribute name="MID" type="xs:string" use="required"/>
			</xs:complexType>
			
</xs:schema>

=== K-Tamas01/N7D1L5_XMLGyak/XML_N7D1L5_Beadandó/XMLN7D1L5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>

<kocsik xmlns:xsi="https://w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="XMLN7D1L5.xsd">
    <elado EID="01">
        <Etulaj>Kis Erno</Etulaj>
        <Eadsz>16516651</Eadsz>
        <Ecim>Miskolc, Kis Erno utca 2</Ecim>
        <Eneve>Muscle Car</Eneve>
    </elado>
    <elado EID="02">
        <Etulaj>Kovacs Janos</Etulaj>
        <Eadsz>16546516</Eadsz>
        <Ecim>Miskolc, Ujgyori Piac 10</Ecim>
        <Eneve>Citroen</Eneve>
    </elado>
    <elado EID="03">
        <Etulaj>Kis Tibor</Etulaj>
        <Eadsz>455464565</Eadsz>
        <Ecim>Miskolc, Kis Tabornok utca 7a</Ecim>
        <Eneve>Lada</Eneve>
    </elado>

    <kiszallitas GYID="01" EID="01"/>
    <kiszallitas GYID="02" EID="03"/>
    <kiszallitas GYID="03" EID="02"/>

    <gyarto GYID="01">
        <gyneve>Dodge</gyneve>
        <gytulaj>Kis Pista</gytulaj>
        <gycim>Budapest, Nagy korut 3</gycim>
        <gyadsz>6541651566</gyadsz>
    </gyarto>
    <gyarto GYID="02">
        <gyneve>Peugeot</gyneve>
        <gytulaj>Kis Bence</gytulaj>
        <gycim>Kapuvar, Nagy korut 3</gycim>
        <gyadsz>6544651651566</gyadsz>
    </gyarto>
    <gyarto GYID="03">
        <gyneve>Ford</gyneve>
        <gytulaj>Kis Ferenc</gytulaj>
        <gycim>Debrecen, Nagy Pista utca 3</gycim>
        <gyadsz>6541651784566</gyadsz>
    </gyarto>

    <gyar GYID="01" DID="01"/>
    <gyar GYID="03" DID="03"/>
    <gyar GYID="02" DID="02"/>

    <dolgozo DID="01">
        <dneve>Jozsef Atilla</dneve>
        <dcime>
            <irsz>1007</irsz>
            <varos>Budapest</varos>
            <utca>Kassai utca 2</utca>
        </dcime>
        <dszul>1987.12.01</dszul>
        <dtel>36204546516</dtel>
    </dolgozo>
    <dolgozo DID="02">
        <dneve>Fekete Peter</dneve>
        <dcime>
            <irsz>7400</irsz>
            <varos>Kaposvár</varos>
            <utca>Szerencsi utca 2</utca>
        </dcime>
        <dszul>1987.12.01</dszul>
        <dtel>36204546516</dtel>
    </dolgozo>
    <dolgozo DID="03">
        <dneve>Petofi Sandor</dneve>
        <dcime>
            <irsz>3527</irsz>
            <varos>Miskolc</varos>
            <utca>Soltész Nagy Kálmán utca 7</utca>
        </dcime>
        <dszul>1987.12.01</dszul>
        <dtel>36204546516</dtel>
    </dolgozo>

    <gyar GYID="01" KID="01"/>
    <gyar GYID="02" KID="02"/>
    <gyar GYID="03" KID="03"/>


    <auto KID="01">
        <kneve>Dodge Challanger Demon</kneve>
        <ktip>Sedan</ktip>
        <khajt>Hatso</khajt>
    </auto>
    <auto KID="02">
        <kneve>Peugeot 403</kneve>
        <ktip>Sedan</ktip>
        <khajt>Elso</khajt>
    </auto>
    <auto KID="03">
        <kneve>Ford Raptor</kneve>
        <ktip>Terep</ktip>
        <khajt>Ossz</khajt>
    </auto>

    <alkatresz KID="01" MID="01"/>
    <alkatresz KID="02" MID="02"/>
    <alkatresz KID="03" MID="03"/>

    <motor MID="01">
        <urtart>6400</urtart>
        <mtip>Benzin</mtip>
        <telj>1000</telj>
    </motor>
    <motor MID="02">
        <urtart>1400</urtart>
        <mtip>Dizel</mtip>
        <telj>150</telj>
    </motor>
    <motor MID="03">
        <urtart>3200</urtart>
        <mtip>Benzin</mtip>
        <telj>380</telj>
    </motor>
</kocsik>
